### ISSUE TITLE
Early Call to Object

### ISSUE THREAD

**Issue by healthykids** [ABCD-STUDY/analysis-nda#12]
Where this is run:
_nda18$eventname = factor(nda18$eventname, levels(nda18$eventname)[c(2,4,1,3)])_
nda18 has not yet been initialized.

looks like nda18 is created 5 blocks lower (nda18 = t2[[1]])

**Comment by HaukeBartsch** [comment]
Yes, correct, thanks for reporting this bug. I just fixed this issue by moving the code down.
